### PR TITLE
Rename kafka topic

### PR DESCRIPTION
**Pull request by griffinhadfield**
Addressing https://github.com/OpenLiberty/guides-common/issues/536

Renamed `systemLoadTopic` to `system.load` 

Also had to redo two of the diagrams to include the updated topic name

### CODE REVIEW

**Review by AustinSeto — CHANGES_REQUESTED** [review]
Running from `finish` directory I see nothing in the inventory service and when I check the docker logs of the container with the system service, I see the following.

```
[ERROR   ] CWMRX1003E: An error occurred when sending a message to the Kafka broker. The error is: org.apache.kafka.common.errors.TimeoutException: Topic system.load not present in metadata after 60000 ms.
```

Couldn't find the cause myself, looked like the system service was sending out the same thing the inventory service was expecting.

***

Also noticed some outdated dependencies in `pom.xml` files.

`kafka-clients` latest version is 2.6.0
`liberty-maven-plugin` latest version is 3.2.3

**Comment by griffinhadfield** [comment]
@AustinSeto I just tested it again and it seems that everything is working. I'm not receiving errors in any of the pods and the endpoint/application is working as expected.

Perhaps there were some leftover artifacts from the old version causing this error and an `mvn clean` would fix it.

The issue could also be that the startup of the container is happening too slowly, perhaps there are too many other containers running or not enough resources. Restarting the docker daemon may fix it. 

Let me know if it still doesn't work after trying those.

**Comment by griffinhadfield** [comment]
Looks like updating the versions of the dependencies is what is causing the error, the lower versions work, but upon upgrading, the guide breaks. I will investigate further.

**Comment by AustinSeto** [comment]
Ran application on older version of plugins, can confirm that older versions do actually work.

**Review by AustinSeto — APPROVED** [review]
LGTM

**Review by gkwan-ibm — CHANGES_REQUESTED** [review]
@griffinhadfield assets/reactive-messaging-system-inventory-detail.png should update `@Outgoing("SystemLoad")` to `@Outgoing("systemLoad")`

**Comment by griffinhadfield** [comment]
@gkwan-ibm 

> @griffinhadfield assets/reactive-messaging-system-inventory-detail.png should update `@Outgoing("SystemLoad")` to `@Outgoing("systemLoad")`

Thank you, I have updated the diagrams - see http://lgdev1.fyre.ibm.com:4020/guides/microprofile-reactive-messaging

**Comment by gkwan-ibm** [comment]
> 
> Thank you, I have updated the diagrams - see http://lgdev1.fyre.ibm.com:4020/guides/microprofile-reactive-messaging


reactive-messaging-system-inventory-detail.png  is not fixed yet. For the InventoryResource, should be `@Incoming`

**Comment by griffinhadfield** [comment]
@gkwan-ibm 

Sorry, I accidentally introduced that mistake when fixing the other one. I have now fixed it: http://lgdev1.fyre.ibm.com:4020/guides/microprofile-reactive-messaging

**Review by gkwan-ibm — APPROVED** [review]

**Pull request merged**
